### ISSUE TITLE
Problems with github_actions in docker_build job 

### ISSUE THREAD

**Issue by zavarin-michael** [HackSoftware/Django-Styleguide-Example#311]
Problem occurs if you write django.yml like this:
```
docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create env file
      run: touch .env
    - name: Build docker
      run: docker-compose build
    - name: Run migrations
      run: docker-compose run django python manage.py migrate 
```

You will get
```
django.db.utils.OperationalError: could not connect to server: Connection refused
	Is the server running on host "db" (172.18.0.2) and accepting
	TCP/IP connections on port 5432?
```

It is because first time django command executes before postgres container completely build.
I researched that postgres shuts down before full build and after that other containers start building.
So if we use migrate command github_action will fail.
![image](https://user-images.githubusercontent.com/33755295/209442105-16325bc9-ab1d-4a10-8ad1-475a9a20eb95.png)

Please, warn other developers about this problem or modify django.yml file.
